version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.0

jobs:
  prepare_data:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      - run: aws s3 cp s3://petes-s3-bucket/Dataset+2024-11-07.csv.
      - run: python prepare_data.py
      - run: aws s3 cp processed_dataset.csv s3://petes-s3-bucket/processed_dataset.csv

  train_model:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      - run: aws s3 cp s3://petes-s3-bucket/processed_dataset.csv .
      - run: python train_model.py
      - run: aws s3 cp trained_dataset.csv s3://petes-s3-bucket/processed_dataset.csv

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - prepare_data
      - train_model

